name: Trigger auto deployment for test22

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test22-AutoDeployTrigger-ad1180f1-b244-4b4c-a85a-bba3c923ac88.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TEST22_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: skuyit47.azurecr.io
          registryUsername: ${{ secrets.TEST22_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST22_REGISTRY_PASSWORD }}
          containerAppName: test22
          resourceGroup: abcom2_group
          imageToBuild: skuyit47.azurecr.io/test22:${{ github.sha }}
          

     

